[project]
name = "repl-nix-neuralaccesspsyche"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.6",
    "guidance>=0.1.16",
    "numpy>=2.2.1",
    "pydantic>=2.10.4",
    "python-multipart>=0.0.20",
    "starlette>=0.41.3",
    "transformers>=4.47.1",
    "uvicorn>=0.34.0",
]
